language: scala
scala:
  - 2.11.8

# Setup ArangoDB
env:
  - ARANGO_DB_VERSION=2.8.7 SCARANGO_VERSION=0.3.1-SNAPSHOT
before_script:
  - "./src/test/travis/publishingMock.sh"
  - "./src/test/travis/arangodb.sh"

# Tricks to avoid unnecessary cache updates
after_script:
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

# These directories are cached to S3 at the end of the build
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
    - $HOME/.sbt/launchers/0.13.9/
    - $TRAVIS_BUILD_DIR/src/test/travis/

jdk:
  - oraclejdk8
  - openjdk6